/******************************************************************************/
/* INCLUDE DATEI FUER CLIENT/SERVER-PIPE ANWENDUNG                            */
/******************************************************************************/


 #define L_KUNDESCHALTER_IDFNR                11
 #define L_KUNDESCHALTER_SKDWERBEFACHBELEGT   1
 #define L_KUNDESCHALTER_SKDKDFACHAKTIV       1
 #define L_KUNDESCHALTER_SKDNATRARESTAKZEPT   1
 #define L_KUNDESCHALTER_SKDNETTOAKTION       1
 #define L_KUNDESCHALTER_SKDETIKETTSERVICE    1
 #define L_KUNDESCHALTER_SKDDEFEKTLIEFERN     1
 #define L_KUNDESCHALTER_SKDDEFEKTABSAGEN     1
 #define L_KUNDESCHALTER_SKDSAMMLDAFUE        1
 #define L_KUNDESCHALTER_SKDAPOEKSTATISITIK   1
 #define L_KUNDESCHALTER_SKDAUTOERHOEHGNNNR   1
 #define L_KUNDESCHALTER_SKDDEFEKTMELDGAUSW   1
 #define L_KUNDESCHALTER_SKDKONTRKOBELEGE     1
 #define L_KUNDESCHALTER_SKDAUFTRAGZUSAMMEN   1
 #define L_KUNDESCHALTER_SKDMWSTHALB          1
 #define L_KUNDESCHALTER_SKDSTADTKUNDE        1
 #define L_KUNDESCHALTER_SKDVALUTASPERRE      1
 #define L_KUNDESCHALTER_SKDSCHWERPUNKT1      1
 #define L_KUNDESCHALTER_SKDSCHWERPUNKT2      1
 #define L_KUNDESCHALTER_SKDSCHWERPUNKT3      1
 #define L_KUNDESCHALTER_SKDSCHWERPUNKT4      1
 #define L_KUNDESCHALTER_SKDSCHWERPUNKT5      1
 #define L_KUNDESCHALTER_SKDVERBUNDGANZ       1
 #define L_KUNDESCHALTER_SKDABSCHLAGRECHN     1
 #define L_KUNDESCHALTER_SKDKDKRITISCH        1
 #define L_KUNDESCHALTER_SKDEILSPERRE         1
 #define L_KUNDESCHALTER_SKDABSAGEN           1
 #define L_KUNDESCHALTER_SKDVIPKUNDE          1
 #define L_KUNDESCHALTER_SKDAUFTRAGSPLIT      1
 #define L_KUNDESCHALTER_SKDMUSSKOPF          1
 #define L_KUNDESCHALTER_SKDSEPAUFT           1
 #define L_KUNDESCHALTER_SKDAUFTRAGZURUECK    1
 #define L_KUNDESCHALTER_SKDBESTZEIT          1
 #define L_KUNDESCHALTER_SKDWIRDBEARB         1
 #define L_KUNDESCHALTER_KZUPD                1
 #define L_KUNDESCHALTER_SKDREIMPORT          1
 #define L_KUNDESCHALTER_SKDWARENACHLIEFERN   1
 #define L_KUNDESCHALTER_SKDPINKUNDE          1
 #define L_KUNDESCHALTER_SKDADGKUNDE          1
 #define L_KUNDESCHALTER_SKDDRUCKBETAPHARM    1
 #define L_KUNDESCHALTER_SKDFAX400            1
 #define L_KUNDESCHALTER_SKDKUNDEAEGESPERRT   1
 #define L_KUNDESCHALTER_SKDDRUCKETIKETT      1
 #define L_KUNDESCHALTER_SKDDRUCKTIERARZNEI   1
 #define L_KUNDESCHALTER_SKDDRUCKKAUFSTRUKT   1
 #define L_KUNDESCHALTER_SKDKAUFSTRUKTART     1
 #define L_KUNDESCHALTER_SKDMONATSRABATT      1
 #define L_KUNDESCHALTER_SKDDRUCKUMSATZ       1
 #define L_KUNDESCHALTER_VERTRIEBSZENTRUMNR   6
 #define L_KUNDESCHALTER_KUNDENNR             11
 #define L_KUNDESCHALTER_TM_DATE              11
 #define L_KUNDESCHALTER_TM_TIME              11
 #define L_KUNDESCHALTER_LOGINID              11
 #define L_KUNDESCHALTER_CHANGEID             1
 #define L_KUNDESCHALTER_SKDBLICKPUNKTABO     1
 #define L_KUNDESCHALTER_SKDBUECHER           1
 #define L_KUNDESCHALTER_SKDVERTRIEBBINDUNG   1
 #define L_KUNDESCHALTER_SKDPOOL              1
 #define L_KUNDESCHALTER_SKDBOUHON            1
 #define L_KUNDESCHALTER_SKDROCHE             1
 #define L_KUNDESCHALTER_SKDVICHY             1
 #define L_KUNDESCHALTER_SKDVBFILIALEMELD     1
 #define L_KUNDESCHALTER_SKDRRABSCHLUSS       1
 #define L_KUNDESCHALTER_SKDABSCHLUSSEIL      1
 #define L_KUNDESCHALTER_SKDTRENNALPHATEXT    1
 #define L_KUNDESCHALTER_SKDRR0800			  1
 #define L_KUNDESCHALTER_SKDTRENNALPHAURR     1
 #define L_KUNDESCHALTER_SKDORIGINALMELD      1
 #define L_KUNDESCHALTER_SKDMIDAS		      1


 #define L_KUNDESCHALTER_PKEY 0

#if defined (BUF_DESC) || defined (C_BUF_DESC)

 #define KUNDESCHALTER_ANZ ( sizeof(KUNDESCHALTER_BES) / sizeof(struct buf_desc) )
#endif
 #define G_KUNDESCHALTER sizeof(struct KUNDESCHALTER)


 #define KUNDESCHALTER_H

 #define KUNDESCHALTER_LISTE \
 			KUNDESCHALTER.IDFNR, \
 			KUNDESCHALTER.SKDWERBEFACHBELEGT, \
 			KUNDESCHALTER.SKDKDFACHAKTIV, \
 			KUNDESCHALTER.SKDNATRARESTAKZEPT, \
 			KUNDESCHALTER.SKDNETTOAKTION, \
 			KUNDESCHALTER.SKDETIKETTSERVICE, \
 			KUNDESCHALTER.SKDDEFEKTLIEFERN, \
 			KUNDESCHALTER.SKDDEFEKTABSAGEN, \
 			KUNDESCHALTER.SKDSAMMLDAFUE, \
 			KUNDESCHALTER.SKDAPOEKSTATISITIK, \
 			KUNDESCHALTER.SKDAUTOERHOEHGNNNR, \
 			KUNDESCHALTER.SKDDEFEKTMELDGAUSW, \
 			KUNDESCHALTER.SKDKONTRKOBELEGE, \
 			KUNDESCHALTER.SKDAUFTRAGZUSAMMEN, \
 			KUNDESCHALTER.SKDMWSTHALB, \
 			KUNDESCHALTER.SKDSTADTKUNDE, \
 			KUNDESCHALTER.SKDVALUTASPERRE, \
 			KUNDESCHALTER.SKDSCHWERPUNKT1, \
 			KUNDESCHALTER.SKDSCHWERPUNKT2, \
 			KUNDESCHALTER.SKDSCHWERPUNKT3, \
 			KUNDESCHALTER.SKDSCHWERPUNKT4, \
 			KUNDESCHALTER.SKDSCHWERPUNKT5, \
 			KUNDESCHALTER.SKDVERBUNDGANZ, \
 			KUNDESCHALTER.SKDABSCHLAGRECHN, \
 			KUNDESCHALTER.SKDKDKRITISCH, \
 			KUNDESCHALTER.SKDEILSPERRE, \
 			KUNDESCHALTER.SKDABSAGEN, \
 			KUNDESCHALTER.SKDVIPKUNDE, \
 			KUNDESCHALTER.SKDAUFTRAGSPLIT, \
 			KUNDESCHALTER.SKDMUSSKOPF, \
 			KUNDESCHALTER.SKDSEPAUFT, \
 			KUNDESCHALTER.SKDAUFTRAGZURUECK, \
 			KUNDESCHALTER.SKDBESTZEIT, \
 			KUNDESCHALTER.SKDWIRDBEARB, \
 			KUNDESCHALTER.KZUPD, \
 			KUNDESCHALTER.SKDREIMPORT, \
 			KUNDESCHALTER.SKDWARENACHLIEFERN, \
 			KUNDESCHALTER.SKDPINKUNDE, \
 			KUNDESCHALTER.SKDADGKUNDE, \
 			KUNDESCHALTER.SKDDRUCKBETAPHARM, \
 			KUNDESCHALTER.SKDFAX400, \
 			KUNDESCHALTER.SKDKUNDEAEGESPERRT, \
 			KUNDESCHALTER.SKDDRUCKETIKETT, \
 			KUNDESCHALTER.SKDDRUCKTIERARZNEI, \
 			KUNDESCHALTER.SKDDRUCKKAUFSTRUKT, \
 			KUNDESCHALTER.SKDKAUFSTRUKTART, \
 			KUNDESCHALTER.SKDMONATSRABATT, \
 			KUNDESCHALTER.SKDDRUCKUMSATZ, \
 			KUNDESCHALTER.VERTRIEBSZENTRUMNR, \
 			KUNDESCHALTER.KUNDENNR, \
 			KUNDESCHALTER.TM_DATE, \
 			KUNDESCHALTER.TM_TIME, \
 			KUNDESCHALTER.LOGINID, \
 			KUNDESCHALTER.CHANGEID, \
 			KUNDESCHALTER.SKDBLICKPUNKTABO, \
 			KUNDESCHALTER.SKDBUECHER, \
 			KUNDESCHALTER.SKDVERTRIEBBINDUNG, \
 			KUNDESCHALTER.SKDPOOL, \
 			KUNDESCHALTER.SKDBOUHON, \
 			KUNDESCHALTER.SKDROCHE, \
 			KUNDESCHALTER.SKDVICHY, \
 			KUNDESCHALTER.SKDVBFILIALEMELD, \
 			KUNDESCHALTER.SKDRRABSCHLUSS, \
 			KUNDESCHALTER.SKDABSCHLUSSEIL, \
 			KUNDESCHALTER.SKDTRENNALPHATEXT, \
 			KUNDESCHALTER.SKDRR0800, \
 			KUNDESCHALTER.SKDTRENNALPHAURR, \
 			KUNDESCHALTER.SKDORIGINALMELD, \
 			KUNDESCHALTER.SKDMIDAS
 #define KUNDESCHALTER_PLISTE \
 			"KUNDESCHALTER.IDFNR," \
 			"KUNDESCHALTER.SKDWERBEFACHBELEGT," \
 			"KUNDESCHALTER.SKDKDFACHAKTIV," \
 			"KUNDESCHALTER.SKDNATRARESTAKZEPT," \
 			"KUNDESCHALTER.SKDNETTOAKTION," \
 			"KUNDESCHALTER.SKDETIKETTSERVICE," \
 			"KUNDESCHALTER.SKDDEFEKTLIEFERN," \
 			"KUNDESCHALTER.SKDDEFEKTABSAGEN," \
 			"KUNDESCHALTER.SKDSAMMLDAFUE," \
 			"KUNDESCHALTER.SKDAPOEKSTATISITIK," \
 			"KUNDESCHALTER.SKDAUTOERHOEHGNNNR," \
 			"KUNDESCHALTER.SKDDEFEKTMELDGAUSW," \
 			"KUNDESCHALTER.SKDKONTRKOBELEGE," \
 			"KUNDESCHALTER.SKDAUFTRAGZUSAMMEN," \
 			"KUNDESCHALTER.SKDMWSTHALB," \
 			"KUNDESCHALTER.SKDSTADTKUNDE," \
 			"KUNDESCHALTER.SKDVALUTASPERRE," \
 			"KUNDESCHALTER.SKDSCHWERPUNKT1," \
 			"KUNDESCHALTER.SKDSCHWERPUNKT2," \
 			"KUNDESCHALTER.SKDSCHWERPUNKT3," \
 			"KUNDESCHALTER.SKDSCHWERPUNKT4," \
 			"KUNDESCHALTER.SKDSCHWERPUNKT5," \
 			"KUNDESCHALTER.SKDVERBUNDGANZ," \
 			"KUNDESCHALTER.SKDABSCHLAGRECHN," \
 			"KUNDESCHALTER.SKDKDKRITISCH," \
 			"KUNDESCHALTER.SKDEILSPERRE," \
 			"KUNDESCHALTER.SKDABSAGEN," \
 			"KUNDESCHALTER.SKDVIPKUNDE," \
 			"KUNDESCHALTER.SKDAUFTRAGSPLIT," \
 			"KUNDESCHALTER.SKDMUSSKOPF," \
 			"KUNDESCHALTER.SKDSEPAUFT," \
 			"KUNDESCHALTER.SKDAUFTRAGZURUECK," \
 			"KUNDESCHALTER.SKDBESTZEIT," \
 			"KUNDESCHALTER.SKDWIRDBEARB," \
 			"KUNDESCHALTER.KZUPD," \
 			"KUNDESCHALTER.SKDREIMPORT," \
 			"KUNDESCHALTER.SKDWARENACHLIEFERN," \
 			"KUNDESCHALTER.SKDPINKUNDE," \
 			"KUNDESCHALTER.SKDADGKUNDE," \
 			"KUNDESCHALTER.SKDDRUCKBETAPHARM," \
 			"KUNDESCHALTER.SKDFAX400," \
 			"KUNDESCHALTER.SKDKUNDEAEGESPERRT," \
 			"KUNDESCHALTER.SKDDRUCKETIKETT," \
 			"KUNDESCHALTER.SKDDRUCKTIERARZNEI," \
 			"KUNDESCHALTER.SKDDRUCKKAUFSTRUKT," \
 			"KUNDESCHALTER.SKDKAUFSTRUKTART," \
 			"KUNDESCHALTER.SKDMONATSRABATT," \
 			"KUNDESCHALTER.SKDDRUCKUMSATZ," \
 			"KUNDESCHALTER.VERTRIEBSZENTRUMNR," \
 			"KUNDESCHALTER.KUNDENNR," \
 			"KUNDESCHALTER.TM_DATE," \
 			"KUNDESCHALTER.TM_TIME," \
 			"KUNDESCHALTER.LOGINID," \
 			"KUNDESCHALTER.CHANGEID," \
 			"KUNDESCHALTER.SKDBLICKPUNKTABO," \
 			"KUNDESCHALTER.SKDBUECHER," \
 			"KUNDESCHALTER.SKDVERTRIEBBINDUNG," \
 			"KUNDESCHALTER.SKDPOOL," \
 			"KUNDESCHALTER.SKDBOUHON," \
 			"KUNDESCHALTER.SKDROCHE," \
 			"KUNDESCHALTER.SKDVICHY," \
 			"KUNDESCHALTER.SKDVBFILIALEMELD," \
 			"KUNDESCHALTER.SKDRRABSCHLUSS," \
 			"KUNDESCHALTER.SKDABSCHLUSSEIL," \
 			"KUNDESCHALTER.SKDTRENNALPHATEXT," \
 			"KUNDESCHALTER.SKDRR0800," \
 			"KUNDESCHALTER.SKDTRENNALPHAURR," \
 			"KUNDESCHALTER.SKDORIGINALMELD," \
 			"KUNDESCHALTER.SKDMIDAS "

 #define KUNDESCHALTER_PELISTE \
 			"IDFNR," \
 			"SKDWERBEFACHBELEGT," \
 			"SKDKDFACHAKTIV," \
 			"SKDNATRARESTAKZEPT," \
 			"SKDNETTOAKTION," \
 			"SKDETIKETTSERVICE," \
 			"SKDDEFEKTLIEFERN," \
 			"SKDDEFEKTABSAGEN," \
 			"SKDSAMMLDAFUE," \
 			"SKDAPOEKSTATISITIK," \
 			"SKDAUTOERHOEHGNNNR," \
 			"SKDDEFEKTMELDGAUSW," \
 			"SKDKONTRKOBELEGE," \
 			"SKDAUFTRAGZUSAMMEN," \
 			"SKDMWSTHALB," \
 			"SKDSTADTKUNDE," \
 			"SKDVALUTASPERRE," \
 			"SKDSCHWERPUNKT1," \
 			"SKDSCHWERPUNKT2," \
 			"SKDSCHWERPUNKT3," \
 			"SKDSCHWERPUNKT4," \
 			"SKDSCHWERPUNKT5," \
 			"SKDVERBUNDGANZ," \
 			"SKDABSCHLAGRECHN," \
 			"SKDKDKRITISCH," \
 			"SKDEILSPERRE," \
 			"SKDABSAGEN," \
 			"SKDVIPKUNDE," \
 			"SKDAUFTRAGSPLIT," \
 			"SKDMUSSKOPF," \
 			"SKDSEPAUFT," \
 			"SKDAUFTRAGZURUECK," \
 			"SKDBESTZEIT," \
 			"SKDWIRDBEARB," \
 			"KZUPD," \
 			"SKDREIMPORT," \
 			"SKDWARENACHLIEFERN," \
 			"SKDPINKUNDE," \
 			"SKDADGKUNDE," \
 			"SKDDRUCKBETAPHARM," \
 			"SKDFAX400," \
 			"SKDKUNDEAEGESPERRT," \
 			"SKDDRUCKETIKETT," \
 			"SKDDRUCKTIERARZNEI," \
 			"SKDDRUCKKAUFSTRUKT," \
 			"SKDKAUFSTRUKTART," \
 			"SKDMONATSRABATT," \
 			"SKDDRUCKUMSATZ," \
 			"VERTRIEBSZENTRUMNR," \
 			"KUNDENNR," \
 			"TM_DATE," \
 			"TM_TIME," \
 			"LOGINID," \
 			"CHANGEID," \
 			"SKDBLICKPUNKTABO," \
 			"SKDBUECHER," \
 			"SKDVERTRIEBBINDUNG," \
 			"SKDPOOL," \
 			"SKDBOUHON," \
 			"SKDROCHE," \
 			"SKDVICHY," \
 			"SKDVBFILIALEMELD," \
 			"SKDRRABSCHLUSS," \
 			"SKDABSCHLUSSEIL," \
 			"SKDTRENNALPHATEXT," \
 			"SKDRR0800," \
 			"SKDTRENNALPHAURR," \
 			"SKDORIGINALMELD," \
 			"SKDMIDAS "

 #define KUNDESCHALTER_UPDLISTE \
 			"IDFNR=?," \
 			"SKDWERBEFACHBELEGT=?," \
 			"SKDKDFACHAKTIV=?," \
 			"SKDNATRARESTAKZEPT=?," \
 			"SKDNETTOAKTION=?," \
 			"SKDETIKETTSERVICE=?," \
 			"SKDDEFEKTLIEFERN=?," \
 			"SKDDEFEKTABSAGEN=?," \
 			"SKDSAMMLDAFUE=?," \
 			"SKDAPOEKSTATISITIK=?," \
 			"SKDAUTOERHOEHGNNNR=?," \
 			"SKDDEFEKTMELDGAUSW=?," \
 			"SKDKONTRKOBELEGE=?," \
 			"SKDAUFTRAGZUSAMMEN=?," \
 			"SKDMWSTHALB=?," \
 			"SKDSTADTKUNDE=?," \
 			"SKDVALUTASPERRE=?," \
 			"SKDSCHWERPUNKT1=?," \
 			"SKDSCHWERPUNKT2=?," \
 			"SKDSCHWERPUNKT3=?," \
 			"SKDSCHWERPUNKT4=?," \
 			"SKDSCHWERPUNKT5=?," \
 			"SKDVERBUNDGANZ=?," \
 			"SKDABSCHLAGRECHN=?," \
 			"SKDKDKRITISCH=?," \
 			"SKDEILSPERRE=?," \
 			"SKDABSAGEN=?," \
 			"SKDVIPKUNDE=?," \
 			"SKDAUFTRAGSPLIT=?," \
 			"SKDMUSSKOPF=?," \
 			"SKDSEPAUFT=?," \
 			"SKDAUFTRAGZURUECK=?," \
 			"SKDBESTZEIT=?," \
 			"SKDWIRDBEARB=?," \
 			"KZUPD=?," \
 			"SKDREIMPORT=?," \
 			"SKDWARENACHLIEFERN=?," \
 			"SKDPINKUNDE=?," \
 			"SKDADGKUNDE=?," \
 			"SKDDRUCKBETAPHARM=?," \
 			"SKDFAX400=?," \
 			"SKDKUNDEAEGESPERRT=?," \
 			"SKDDRUCKETIKETT=?," \
 			"SKDDRUCKTIERARZNEI=?," \
 			"SKDDRUCKKAUFSTRUKT=?," \
 			"SKDKAUFSTRUKTART=?," \
 			"SKDMONATSRABATT=?," \
 			"SKDDRUCKUMSATZ=?," \
 			"VERTRIEBSZENTRUMNR=?," \
 			"KUNDENNR=?," \
 			"TM_DATE=?," \
 			"TM_TIME=?," \
 			"LOGINID=?," \
 			"CHANGEID=?," \
 			"SKDBLICKPUNKTABO=?," \
 			"SKDBUECHER=?," \
 			"SKDVERTRIEBBINDUNG=?," \
 			"SKDPOOL=?," \
 			"SKDBOUHON=?," \
 			"SKDROCHE=?," \
 			"SKDVICHY=?," \
 			"SKDVBFILIALEMELD=?," \
 			"SKDRRABSCHLUSS=?," \
 			"SKDABSCHLUSSEIL=?," \
 			"SKDTRENNALPHATEXT=?," \
 			"SKDRR0800=?," \
 			"SKDTRENNALPHAURR=?," \
 			"SKDORIGINALMELD=?," \
 			"SKDMIDAS=?"

 #define KUNDESCHALTERIDFNR                         0
 #define KUNDESCHALTERSKDWERBEFACHBELEGT            1
 #define KUNDESCHALTERSKDKDFACHAKTIV                2
 #define KUNDESCHALTERSKDNATRARESTAKZEPT            3
 #define KUNDESCHALTERSKDNETTOAKTION                4
 #define KUNDESCHALTERSKDETIKETTSERVICE             5
 #define KUNDESCHALTERSKDDEFEKTLIEFERN              6
 #define KUNDESCHALTERSKDDEFEKTABSAGEN              7
 #define KUNDESCHALTERSKDSAMMLDAFUE                 8
 #define KUNDESCHALTERSKDAPOEKSTATISITIK            9
 #define KUNDESCHALTERSKDAUTOERHOEHGNNNR            10
 #define KUNDESCHALTERSKDDEFEKTMELDGAUSW            11
 #define KUNDESCHALTERSKDKONTRKOBELEGE              12
 #define KUNDESCHALTERSKDAUFTRAGZUSAMMEN            13
 #define KUNDESCHALTERSKDMWSTHALB                   14
 #define KUNDESCHALTERSKDSTADTKUNDE                 15
 #define KUNDESCHALTERSKDVALUTASPERRE               16
 #define KUNDESCHALTERSKDSCHWERPUNKT1               17
 #define KUNDESCHALTERSKDSCHWERPUNKT2               18
 #define KUNDESCHALTERSKDSCHWERPUNKT3               19
 #define KUNDESCHALTERSKDSCHWERPUNKT4               20
 #define KUNDESCHALTERSKDSCHWERPUNKT5               21
 #define KUNDESCHALTERSKDVERBUNDGANZ                22
 #define KUNDESCHALTERSKDABSCHLAGRECHN              23
 #define KUNDESCHALTERSKDKDKRITISCH                 24
 #define KUNDESCHALTERSKDEILSPERRE                  25
 #define KUNDESCHALTERSKDABSAGEN                    26
 #define KUNDESCHALTERSKDVIPKUNDE                   27
 #define KUNDESCHALTERSKDAUFTRAGSPLIT               28
 #define KUNDESCHALTERSKDMUSSKOPF                   29
 #define KUNDESCHALTERSKDSEPAUFT                    30
 #define KUNDESCHALTERSKDAUFTRAGZURUECK             31
 #define KUNDESCHALTERSKDBESTZEIT                   32
 #define KUNDESCHALTERSKDWIRDBEARB                  33
 #define KUNDESCHALTERKZUPD                         34
 #define KUNDESCHALTERSKDREIMPORT                   35
 #define KUNDESCHALTERSKDWARENACHLIEFERN            36
 #define KUNDESCHALTERSKDPINKUNDE                   37
 #define KUNDESCHALTERSKDADGKUNDE                   38
 #define KUNDESCHALTERSKDDRUCKBETAPHARM             39
 #define KUNDESCHALTERSKDFAX400                     40
 #define KUNDESCHALTERSKDKUNDEAEGESPERRT            41
 #define KUNDESCHALTERSKDDRUCKETIKETT               42
 #define KUNDESCHALTERSKDDRUCKTIERARZNEI            43
 #define KUNDESCHALTERSKDDRUCKKAUFSTRUKT            44
 #define KUNDESCHALTERSKDKAUFSTRUKTART              45
 #define KUNDESCHALTERSKDMONATSRABATT               46
 #define KUNDESCHALTERSKDDRUCKUMSATZ                47
 #define KUNDESCHALTERVERTRIEBSZENTRUMNR            48
 #define KUNDESCHALTERKUNDENNR                      49
 #define KUNDESCHALTERTM_DATE                       50
 #define KUNDESCHALTERTM_TIME                       51
 #define KUNDESCHALTERLOGINID                       52
 #define KUNDESCHALTERCHANGEID                      53
 #define KUNDESCHALTERSKDBLICKPUNKTABO              54
 #define KUNDESCHALTERSKDBUECHER                    55
 #define KUNDESCHALTERSKDVERTRIEBBINDUNG            56
 #define KUNDESCHALTERSKDPOOL                       57
 #define KUNDESCHALTERSKDBOUHON                     58
 #define KUNDESCHALTERSKDROCHE                      59
 #define KUNDESCHALTERSKDVICHY                      60
 #define KUNDESCHALTERSKDVBFILIALEMELD              61
 #define KUNDESCHALTERSKDRRABSCHLUSS                62
 #define KUNDESCHALTERSKDABSCHLUSSEIL               63
 #define KUNDESCHALTERSKDTRENNALPHATEXT             64
 #define KUNDESCHALTERSKDRR0800						65
 #define KUNDESCHALTERSKDTRENNALPHAURR				66
 #define KUNDESCHALTERSKDORIGINALMELD				67
 #define KUNDESCHALTERSKDMIDAS						68

 #define KUNDESCHALTER_ZEIGER(xxx) \
 			:xxx->IDFNR,\
 			:xxx->SKDWERBEFACHBELEGT,\
 			:xxx->SKDKDFACHAKTIV,\
 			:xxx->SKDNATRARESTAKZEPT,\
 			:xxx->SKDNETTOAKTION,\
 			:xxx->SKDETIKETTSERVICE,\
 			:xxx->SKDDEFEKTLIEFERN,\
 			:xxx->SKDDEFEKTABSAGEN,\
 			:xxx->SKDSAMMLDAFUE,\
 			:xxx->SKDAPOEKSTATISITIK,\
 			:xxx->SKDAUTOERHOEHGNNNR,\
 			:xxx->SKDDEFEKTMELDGAUSW,\
 			:xxx->SKDKONTRKOBELEGE,\
 			:xxx->SKDAUFTRAGZUSAMMEN,\
 			:xxx->SKDMWSTHALB,\
 			:xxx->SKDSTADTKUNDE,\
 			:xxx->SKDVALUTASPERRE,\
 			:xxx->SKDSCHWERPUNKT1,\
 			:xxx->SKDSCHWERPUNKT2,\
 			:xxx->SKDSCHWERPUNKT3,\
 			:xxx->SKDSCHWERPUNKT4,\
 			:xxx->SKDSCHWERPUNKT5,\
 			:xxx->SKDVERBUNDGANZ,\
 			:xxx->SKDABSCHLAGRECHN,\
 			:xxx->SKDKDKRITISCH,\
 			:xxx->SKDEILSPERRE,\
 			:xxx->SKDABSAGEN,\
 			:xxx->SKDVIPKUNDE,\
 			:xxx->SKDAUFTRAGSPLIT,\
 			:xxx->SKDMUSSKOPF,\
 			:xxx->SKDSEPAUFT,\
 			:xxx->SKDAUFTRAGZURUECK,\
 			:xxx->SKDBESTZEIT,\
 			:xxx->SKDWIRDBEARB,\
 			:xxx->KZUPD,\
 			:xxx->SKDREIMPORT,\
 			:xxx->SKDWARENACHLIEFERN,\
 			:xxx->SKDPINKUNDE,\
 			:xxx->SKDADGKUNDE,\
 			:xxx->SKDDRUCKBETAPHARM,\
 			:xxx->SKDFAX400,\
 			:xxx->SKDKUNDEAEGESPERRT,\
 			:xxx->SKDDRUCKETIKETT,\
 			:xxx->SKDDRUCKTIERARZNEI,\
 			:xxx->SKDDRUCKKAUFSTRUKT,\
 			:xxx->SKDKAUFSTRUKTART,\
 			:xxx->SKDMONATSRABATT,\
 			:xxx->SKDDRUCKUMSATZ,\
 			:xxx->VERTRIEBSZENTRUMNR,\
 			:xxx->KUNDENNR,\
 			:xxx->TM_DATE,\
 			:xxx->TM_TIME,\
 			:xxx->LOGINID,\
 			:xxx->CHANGEID,\
 			:xxx->SKDBLICKPUNKTABO,\
 			:xxx->SKDBUECHER,\
 			:xxx->SKDVERTRIEBBINDUNG,\
 			:xxx->SKDPOOL,\
 			:xxx->SKDBOUHON,\
 			:xxx->SKDROCHE,\
 			:xxx->SKDVICHY,\
 			:xxx->SKDVBFILIALEMELD,\
 			:xxx->SKDRRABSCHLUSS,\
 			:xxx->SKDABSCHLUSSEIL,\
 			:xxx->SKDTRENNALPHATEXT,\
 			:xxx->SKDRR0800,\
 			:xxx->SKDTRENNALPHAURR,\
 			:xxx->SKDORIGINALMELD,\
 			:xxx->SKDMIDAS

 #define KUNDESCHALTER_UPDATE(xxx) \
 			IDFNR = :xxx->IDFNR,\
 			SKDWERBEFACHBELEGT = :xxx->SKDWERBEFACHBELEGT,\
 			SKDKDFACHAKTIV = :xxx->SKDKDFACHAKTIV,\
 			SKDNATRARESTAKZEPT = :xxx->SKDNATRARESTAKZEPT,\
 			SKDNETTOAKTION = :xxx->SKDNETTOAKTION,\
 			SKDETIKETTSERVICE = :xxx->SKDETIKETTSERVICE,\
 			SKDDEFEKTLIEFERN = :xxx->SKDDEFEKTLIEFERN,\
 			SKDDEFEKTABSAGEN = :xxx->SKDDEFEKTABSAGEN,\
 			SKDSAMMLDAFUE = :xxx->SKDSAMMLDAFUE,\
 			SKDAPOEKSTATISITIK = :xxx->SKDAPOEKSTATISITIK,\
 			SKDAUTOERHOEHGNNNR = :xxx->SKDAUTOERHOEHGNNNR,\
 			SKDDEFEKTMELDGAUSW = :xxx->SKDDEFEKTMELDGAUSW,\
 			SKDKONTRKOBELEGE = :xxx->SKDKONTRKOBELEGE,\
 			SKDAUFTRAGZUSAMMEN = :xxx->SKDAUFTRAGZUSAMMEN,\
 			SKDMWSTHALB = :xxx->SKDMWSTHALB,\
 			SKDSTADTKUNDE = :xxx->SKDSTADTKUNDE,\
 			SKDVALUTASPERRE = :xxx->SKDVALUTASPERRE,\
 			SKDSCHWERPUNKT1 = :xxx->SKDSCHWERPUNKT1,\
 			SKDSCHWERPUNKT2 = :xxx->SKDSCHWERPUNKT2,\
 			SKDSCHWERPUNKT3 = :xxx->SKDSCHWERPUNKT3,\
 			SKDSCHWERPUNKT4 = :xxx->SKDSCHWERPUNKT4,\
 			SKDSCHWERPUNKT5 = :xxx->SKDSCHWERPUNKT5,\
 			SKDVERBUNDGANZ = :xxx->SKDVERBUNDGANZ,\
 			SKDABSCHLAGRECHN = :xxx->SKDABSCHLAGRECHN,\
 			SKDKDKRITISCH = :xxx->SKDKDKRITISCH,\
 			SKDEILSPERRE = :xxx->SKDEILSPERRE,\
 			SKDABSAGEN = :xxx->SKDABSAGEN,\
 			SKDVIPKUNDE = :xxx->SKDVIPKUNDE,\
 			SKDAUFTRAGSPLIT = :xxx->SKDAUFTRAGSPLIT,\
 			SKDMUSSKOPF = :xxx->SKDMUSSKOPF,\
 			SKDSEPAUFT = :xxx->SKDSEPAUFT,\
 			SKDAUFTRAGZURUECK = :xxx->SKDAUFTRAGZURUECK,\
 			SKDBESTZEIT = :xxx->SKDBESTZEIT,\
 			SKDWIRDBEARB = :xxx->SKDWIRDBEARB,\
 			KZUPD = :xxx->KZUPD,\
 			SKDREIMPORT = :xxx->SKDREIMPORT,\
 			SKDWARENACHLIEFERN = :xxx->SKDWARENACHLIEFERN,\
 			SKDPINKUNDE = :xxx->SKDPINKUNDE,\
 			SKDADGKUNDE = :xxx->SKDADGKUNDE,\
 			SKDDRUCKBETAPHARM = :xxx->SKDDRUCKBETAPHARM,\
 			SKDFAX400 = :xxx->SKDFAX400,\
 			SKDKUNDEAEGESPERRT = :xxx->SKDKUNDEAEGESPERRT,\
 			SKDDRUCKETIKETT = :xxx->SKDDRUCKETIKETT,\
 			SKDDRUCKTIERARZNEI = :xxx->SKDDRUCKTIERARZNEI,\
 			SKDDRUCKKAUFSTRUKT = :xxx->SKDDRUCKKAUFSTRUKT,\
 			SKDKAUFSTRUKTART = :xxx->SKDKAUFSTRUKTART,\
 			SKDMONATSRABATT = :xxx->SKDMONATSRABATT,\
 			SKDDRUCKUMSATZ = :xxx->SKDDRUCKUMSATZ,\
 			VERTRIEBSZENTRUMNR = :xxx->VERTRIEBSZENTRUMNR,\
 			KUNDENNR = :xxx->KUNDENNR,\
 			TM_DATE = :xxx->TM_DATE,\
 			TM_TIME = :xxx->TM_TIME,\
 			LOGINID = :xxx->LOGINID,\
 			CHANGEID = :xxx->CHANGEID,\
 			SKDBLICKPUNKTABO = :xxx->SKDBLICKPUNKTABO,\
 			SKDBUECHER = :xxx->SKDBUECHER,\
 			SKDVERTRIEBBINDUNG = :xxx->SKDVERTRIEBBINDUNG,\
 			SKDPOOL = :xxx->SKDPOOL,\
 			SKDBOUHON = :xxx->SKDBOUHON,\
 			SKDROCHE = :xxx->SKDROCHE,\
 			SKDVICHY = :xxx->SKDVICHY,\
 			SKDVBFILIALEMELD = :xxx->SKDVBFILIALEMELD,\
 			SKDRRABSCHLUSS = :xxx->SKDRRABSCHLUSS,\
 			SKDABSCHLUSSEIL = :xxx->SKDABSCHLUSSEIL,\
 			SKDTRENNALPHATEXT = :xxx->SKDTRENNALPHATEXT,\
 			SKDRR0800 = :xxx->SKDRR0800,\
 			SKDTRENNALPHAURR = :xxx->SKDTRENNALPHAURR,\
 			SKDORIGINALMELD = :xxx->SKDORIGINALMELD,\
 			SKDMIDAS = :xxx->SKDMIDAS

 #define LS_KUNDESCHALTER_IDFNR                11
 #define LS_KUNDESCHALTER_SKDWERBEFACHBELEGT   2
 #define LS_KUNDESCHALTER_SKDKDFACHAKTIV       2
 #define LS_KUNDESCHALTER_SKDNATRARESTAKZEPT   2
 #define LS_KUNDESCHALTER_SKDNETTOAKTION       2
 #define LS_KUNDESCHALTER_SKDETIKETTSERVICE    2
 #define LS_KUNDESCHALTER_SKDDEFEKTLIEFERN     2
 #define LS_KUNDESCHALTER_SKDDEFEKTABSAGEN     2
 #define LS_KUNDESCHALTER_SKDSAMMLDAFUE        2
 #define LS_KUNDESCHALTER_SKDAPOEKSTATISITIK   2
 #define LS_KUNDESCHALTER_SKDAUTOERHOEHGNNNR   2
 #define LS_KUNDESCHALTER_SKDDEFEKTMELDGAUSW   2
 #define LS_KUNDESCHALTER_SKDKONTRKOBELEGE     2
 #define LS_KUNDESCHALTER_SKDAUFTRAGZUSAMMEN   2
 #define LS_KUNDESCHALTER_SKDMWSTHALB          2
 #define LS_KUNDESCHALTER_SKDSTADTKUNDE        2
 #define LS_KUNDESCHALTER_SKDVALUTASPERRE      2
 #define LS_KUNDESCHALTER_SKDSCHWERPUNKT1      2
 #define LS_KUNDESCHALTER_SKDSCHWERPUNKT2      2
 #define LS_KUNDESCHALTER_SKDSCHWERPUNKT3      2
 #define LS_KUNDESCHALTER_SKDSCHWERPUNKT4      2
 #define LS_KUNDESCHALTER_SKDSCHWERPUNKT5      2
 #define LS_KUNDESCHALTER_SKDVERBUNDGANZ       2
 #define LS_KUNDESCHALTER_SKDABSCHLAGRECHN     2
 #define LS_KUNDESCHALTER_SKDKDKRITISCH        2
 #define LS_KUNDESCHALTER_SKDEILSPERRE         2
 #define LS_KUNDESCHALTER_SKDABSAGEN           2
 #define LS_KUNDESCHALTER_SKDVIPKUNDE          2
 #define LS_KUNDESCHALTER_SKDAUFTRAGSPLIT      2
 #define LS_KUNDESCHALTER_SKDMUSSKOPF          2
 #define LS_KUNDESCHALTER_SKDSEPAUFT           2
 #define LS_KUNDESCHALTER_SKDAUFTRAGZURUECK    2
 #define LS_KUNDESCHALTER_SKDBESTZEIT          2
 #define LS_KUNDESCHALTER_SKDWIRDBEARB         2
 #define LS_KUNDESCHALTER_KZUPD                2
 #define LS_KUNDESCHALTER_SKDREIMPORT          2
 #define LS_KUNDESCHALTER_SKDWARENACHLIEFERN   2
 #define LS_KUNDESCHALTER_SKDPINKUNDE          2
 #define LS_KUNDESCHALTER_SKDADGKUNDE          2
 #define LS_KUNDESCHALTER_SKDDRUCKBETAPHARM    2
 #define LS_KUNDESCHALTER_SKDFAX400            2
 #define LS_KUNDESCHALTER_SKDKUNDEAEGESPERRT   2
 #define LS_KUNDESCHALTER_SKDDRUCKETIKETT      2
 #define LS_KUNDESCHALTER_SKDDRUCKTIERARZNEI   2
 #define LS_KUNDESCHALTER_SKDDRUCKKAUFSTRUKT   2
 #define LS_KUNDESCHALTER_SKDKAUFSTRUKTART     2
 #define LS_KUNDESCHALTER_SKDMONATSRABATT      2
 #define LS_KUNDESCHALTER_SKDDRUCKUMSATZ       2
 #define LS_KUNDESCHALTER_VERTRIEBSZENTRUMNR   7
 #define LS_KUNDESCHALTER_KUNDENNR             11
 #define LS_KUNDESCHALTER_TM_DATE              11
 #define LS_KUNDESCHALTER_TM_TIME              11
 #define LS_KUNDESCHALTER_LOGINID              11
 #define LS_KUNDESCHALTER_CHANGEID             2
 #define LS_KUNDESCHALTER_SKDBLICKPUNKTABO     2
 #define LS_KUNDESCHALTER_SKDBUECHER           2
 #define LS_KUNDESCHALTER_SKDVERTRIEBBINDUNG   2
 #define LS_KUNDESCHALTER_SKDPOOL              2
 #define LS_KUNDESCHALTER_SKDBOUHON            2
 #define LS_KUNDESCHALTER_SKDROCHE             2
 #define LS_KUNDESCHALTER_SKDVICHY             2
 #define LS_KUNDESCHALTER_SKDVBFILIALEMELD     2
 #define LS_KUNDESCHALTER_SKDRRABSCHLUSS       2
 #define LS_KUNDESCHALTER_SKDABSCHLUSSEIL      2
 #define LS_KUNDESCHALTER_SKDTRENNALPHATEXT    2
 #define LS_KUNDESCHALTER_SKDRR0800			   2
 #define LS_KUNDESCHALTER_SKDTRENNALPHAURR     2
 #define LS_KUNDESCHALTER_SKDORIGINALMELD	   2
 #define LS_KUNDESCHALTER_SKDMIDAS		       2

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

 struct KUNDESCHALTER {
		 long    IDFNR;
		 char    SKDWERBEFACHBELEGT[1 + 1];
		 char    SKDKDFACHAKTIV[1 + 1];
		 char    SKDNATRARESTAKZEPT[1 + 1];
		 char    SKDNETTOAKTION[1 + 1];
		 char    SKDETIKETTSERVICE[1 + 1];
		 char    SKDDEFEKTLIEFERN[1 + 1];
		 char    SKDDEFEKTABSAGEN[1 + 1];
		 char    SKDSAMMLDAFUE[1 + 1];
		 char    SKDAPOEKSTATISITIK[1 + 1];
		 char    SKDAUTOERHOEHGNNNR[1 + 1];
		 char    SKDDEFEKTMELDGAUSW[1 + 1];
		 char    SKDKONTRKOBELEGE[1 + 1];
		 char    SKDAUFTRAGZUSAMMEN[1 + 1];
		 char    SKDMWSTHALB[1 + 1];
		 char    SKDSTADTKUNDE[1 + 1];
		 char    SKDVALUTASPERRE[1 + 1];
		 char    SKDSCHWERPUNKT1[1 + 1];
		 char    SKDSCHWERPUNKT2[1 + 1];
		 char    SKDSCHWERPUNKT3[1 + 1];
		 char    SKDSCHWERPUNKT4[1 + 1];
		 char    SKDSCHWERPUNKT5[1 + 1];
		 char    SKDVERBUNDGANZ[1 + 1];
		 char    SKDABSCHLAGRECHN[1 + 1];
		 char    SKDKDKRITISCH[1 + 1];
		 char    SKDEILSPERRE[1 + 1];
		 char    SKDABSAGEN[1 + 1];
		 char    SKDVIPKUNDE[1 + 1];
		 char    SKDAUFTRAGSPLIT[1 + 1];
		 char    SKDMUSSKOPF[1 + 1];
		 char    SKDSEPAUFT[1 + 1];
		 char    SKDAUFTRAGZURUECK[1 + 1];
		 char    SKDBESTZEIT[1 + 1];
		 char    SKDWIRDBEARB[1 + 1];
		 char    KZUPD[1 + 1];
		 char    SKDREIMPORT[1 + 1];
		 char    SKDWARENACHLIEFERN[1 + 1];
		 char    SKDPINKUNDE[1 + 1];
		 char    SKDADGKUNDE[1 + 1];
		 char    SKDDRUCKBETAPHARM[1 + 1];
		 char    SKDFAX400[1 + 1];
		 char    SKDKUNDEAEGESPERRT[1 + 1];
		 char    SKDDRUCKETIKETT[1 + 1];
		 char    SKDDRUCKTIERARZNEI[1 + 1];
		 char    SKDDRUCKKAUFSTRUKT[1 + 1];
		 char    SKDKAUFSTRUKTART[1 + 1];
		 char    SKDMONATSRABATT[1 + 1];
		 char    SKDDRUCKUMSATZ[1 + 1];
		 short   VERTRIEBSZENTRUMNR;
		 long    KUNDENNR;
		 long    TM_DATE;
		 long    TM_TIME;
		 long    LOGINID;
		 char    CHANGEID[1 + 1];
		 char    SKDBLICKPUNKTABO[1 + 1];
		 char    SKDBUECHER[1 + 1];
		 char    SKDVERTRIEBBINDUNG[1 + 1];
		 char    SKDPOOL[1 + 1];
		 char    SKDBOUHON[1 + 1];
		 char    SKDROCHE[1 + 1];
		 char    SKDVICHY[1 + 1];
		 char    SKDVBFILIALEMELD[1 + 1];
		 char    SKDRRABSCHLUSS[1 + 1];
		 char    SKDABSCHLUSSEIL[1 + 1];
		 char    SKDTRENNALPHATEXT[1 + 1];
		 char    SKDRR0800[1 + 1];
		 char    SKDTRENNALPHAURR[1 + 1];
		 char    SKDORIGINALMELD[1 + 1];
		 char    SKDMIDAS[1 + 1];
       };

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif


#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

 struct C_KUNDESCHALTER {
		 long    IDFNR;
		 char    SKDWERBEFACHBELEGT;
		 char    SKDKDFACHAKTIV;
		 char    SKDNATRARESTAKZEPT;
		 char    SKDNETTOAKTION;
		 char    SKDETIKETTSERVICE;
		 char    SKDDEFEKTLIEFERN;
		 char    SKDDEFEKTABSAGEN;
		 char    SKDSAMMLDAFUE;
		 char    SKDAPOEKSTATISITIK;
		 char    SKDAUTOERHOEHGNNNR;
		 char    SKDDEFEKTMELDGAUSW;
		 char    SKDKONTRKOBELEGE;
		 char    SKDAUFTRAGZUSAMMEN;
		 char    SKDMWSTHALB;
		 char    SKDSTADTKUNDE;
		 char    SKDVALUTASPERRE;
		 char    SKDSCHWERPUNKT1;
		 char    SKDSCHWERPUNKT2;
		 char    SKDSCHWERPUNKT3;
		 char    SKDSCHWERPUNKT4;
		 char    SKDSCHWERPUNKT5;
		 char    SKDVERBUNDGANZ;
		 char    SKDABSCHLAGRECHN;
		 char    SKDKDKRITISCH;
		 char    SKDEILSPERRE;
		 char    SKDABSAGEN;
		 char    SKDVIPKUNDE;
		 char    SKDAUFTRAGSPLIT;
		 char    SKDMUSSKOPF;
		 char    SKDSEPAUFT;
		 char    SKDAUFTRAGZURUECK;
		 char    SKDBESTZEIT;
		 char    SKDWIRDBEARB;
		 char    KZUPD;
		 char    SKDREIMPORT;
		 char    SKDWARENACHLIEFERN;
		 char    SKDPINKUNDE;
		 char    SKDADGKUNDE;
		 char    SKDDRUCKBETAPHARM;
		 char    SKDFAX400;
		 char    SKDKUNDEAEGESPERRT;
		 char    SKDDRUCKETIKETT;
		 char    SKDDRUCKTIERARZNEI;
		 char    SKDDRUCKKAUFSTRUKT;
		 char    SKDKAUFSTRUKTART;
		 char    SKDMONATSRABATT;
		 char    SKDDRUCKUMSATZ;
		 short   VERTRIEBSZENTRUMNR;
		 long    KUNDENNR;
		 long    TM_DATE;
		 long    TM_TIME;
		 long    LOGINID;
		 char    CHANGEID;
		 char    SKDBLICKPUNKTABO;
		 char    SKDBUECHER;
		 char    SKDVERTRIEBBINDUNG;
		 char    SKDPOOL;
		 char    SKDBOUHON;
		 char    SKDROCHE;
		 char    SKDVICHY;
		 char    SKDVBFILIALEMELD;
		 char    SKDRRABSCHLUSS;
		 char    SKDABSCHLUSSEIL;
		 char    SKDTRENNALPHATEXT;
		 char    SKDRR0800;
		 char    SKDTRENNALPHAURR;
		 char    SKDORIGINALMELD;
		 char    SKDMIDAS;
       };

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif


#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

 struct I_KUNDESCHALTER {
		 short  IDFNR;
		 short  SKDWERBEFACHBELEGT;
		 short  SKDKDFACHAKTIV;
		 short  SKDNATRARESTAKZEPT;
		 short  SKDNETTOAKTION;
		 short  SKDETIKETTSERVICE;
		 short  SKDDEFEKTLIEFERN;
		 short  SKDDEFEKTABSAGEN;
		 short  SKDSAMMLDAFUE;
		 short  SKDAPOEKSTATISITIK;
		 short  SKDAUTOERHOEHGNNNR;
		 short  SKDDEFEKTMELDGAUSW;
		 short  SKDKONTRKOBELEGE;
		 short  SKDAUFTRAGZUSAMMEN;
		 short  SKDMWSTHALB;
		 short  SKDSTADTKUNDE;
		 short  SKDVALUTASPERRE;
		 short  SKDSCHWERPUNKT1;
		 short  SKDSCHWERPUNKT2;
		 short  SKDSCHWERPUNKT3;
		 short  SKDSCHWERPUNKT4;
		 short  SKDSCHWERPUNKT5;
		 short  SKDVERBUNDGANZ;
		 short  SKDABSCHLAGRECHN;
		 short  SKDKDKRITISCH;
		 short  SKDEILSPERRE;
		 short  SKDABSAGEN;
		 short  SKDVIPKUNDE;
		 short  SKDAUFTRAGSPLIT;
		 short  SKDMUSSKOPF;
		 short  SKDSEPAUFT;
		 short  SKDAUFTRAGZURUECK;
		 short  SKDBESTZEIT;
		 short  SKDWIRDBEARB;
		 short  KZUPD;
		 short  SKDREIMPORT;
		 short  SKDWARENACHLIEFERN;
		 short  SKDPINKUNDE;
		 short  SKDADGKUNDE;
		 short  SKDDRUCKBETAPHARM;
		 short  SKDFAX400;
		 short  SKDKUNDEAEGESPERRT;
		 short  SKDDRUCKETIKETT;
		 short  SKDDRUCKTIERARZNEI;
		 short  SKDDRUCKKAUFSTRUKT;
		 short  SKDKAUFSTRUKTART;
		 short  SKDMONATSRABATT;
		 short  SKDDRUCKUMSATZ;
		 short  VERTRIEBSZENTRUMNR;
		 short  KUNDENNR;
		 short  TM_DATE;
		 short  TM_TIME;
		 short  LOGINID;
		 short  CHANGEID;
		 short  SKDBLICKPUNKTABO;
		 short  SKDBUECHER;
		 short  SKDVERTRIEBBINDUNG;
		 short  SKDPOOL;
		 short  SKDBOUHON;
		 short  SKDROCHE;
		 short  SKDVICHY;
		 short  SKDVBFILIALEMELD;
		 short  SKDRRABSCHLUSS;
		 short  SKDABSCHLUSSEIL;
		 short  SKDTRENNALPHATEXT;
		 short  SKDRR0800;
		 short  SKDTRENNALPHAURR;
		 short  SKDORIGINALMELD;
		 short  SKDMIDAS;
       };

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif


#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

 struct S_KUNDESCHALTER {
		 char    IDFNR[11];
		 char    SKDWERBEFACHBELEGT[1 + 1];
		 char    SKDKDFACHAKTIV[1 + 1];
		 char    SKDNATRARESTAKZEPT[1 + 1];
		 char    SKDNETTOAKTION[1 + 1];
		 char    SKDETIKETTSERVICE[1 + 1];
		 char    SKDDEFEKTLIEFERN[1 + 1];
		 char    SKDDEFEKTABSAGEN[1 + 1];
		 char    SKDSAMMLDAFUE[1 + 1];
		 char    SKDAPOEKSTATISITIK[1 + 1];
		 char    SKDAUTOERHOEHGNNNR[1 + 1];
		 char    SKDDEFEKTMELDGAUSW[1 + 1];
		 char    SKDKONTRKOBELEGE[1 + 1];
		 char    SKDAUFTRAGZUSAMMEN[1 + 1];
		 char    SKDMWSTHALB[1 + 1];
		 char    SKDSTADTKUNDE[1 + 1];
		 char    SKDVALUTASPERRE[1 + 1];
		 char    SKDSCHWERPUNKT1[1 + 1];
		 char    SKDSCHWERPUNKT2[1 + 1];
		 char    SKDSCHWERPUNKT3[1 + 1];
		 char    SKDSCHWERPUNKT4[1 + 1];
		 char    SKDSCHWERPUNKT5[1 + 1];
		 char    SKDVERBUNDGANZ[1 + 1];
		 char    SKDABSCHLAGRECHN[1 + 1];
		 char    SKDKDKRITISCH[1 + 1];
		 char    SKDEILSPERRE[1 + 1];
		 char    SKDABSAGEN[1 + 1];
		 char    SKDVIPKUNDE[1 + 1];
		 char    SKDAUFTRAGSPLIT[1 + 1];
		 char    SKDMUSSKOPF[1 + 1];
		 char    SKDSEPAUFT[1 + 1];
		 char    SKDAUFTRAGZURUECK[1 + 1];
		 char    SKDBESTZEIT[1 + 1];
		 char    SKDWIRDBEARB[1 + 1];
		 char    KZUPD[1 + 1];
		 char    SKDREIMPORT[1 + 1];
		 char    SKDWARENACHLIEFERN[1 + 1];
		 char    SKDPINKUNDE[1 + 1];
		 char    SKDADGKUNDE[1 + 1];
		 char    SKDDRUCKBETAPHARM[1 + 1];
		 char    SKDFAX400[1 + 1];
		 char    SKDKUNDEAEGESPERRT[1 + 1];
		 char    SKDDRUCKETIKETT[1 + 1];
		 char    SKDDRUCKTIERARZNEI[1 + 1];
		 char    SKDDRUCKKAUFSTRUKT[1 + 1];
		 char    SKDKAUFSTRUKTART[1 + 1];
		 char    SKDMONATSRABATT[1 + 1];
		 char    SKDDRUCKUMSATZ[1 + 1];
		 char    VERTRIEBSZENTRUMNR[7];
		 char    KUNDENNR[11];
		 char    TM_DATE[11];
		 char    TM_TIME[11];
		 char    LOGINID[11];
		 char    CHANGEID[1 + 1];
		 char    SKDBLICKPUNKTABO[1 + 1];
		 char    SKDBUECHER[1 + 1];
		 char    SKDVERTRIEBBINDUNG[1 + 1];
		 char    SKDPOOL[1 + 1];
		 char    SKDBOUHON[1 + 1];
		 char    SKDROCHE[1 + 1];
		 char    SKDVICHY[1 + 1];
		 char    SKDVBFILIALEMELD[1 + 1];
		 char    SKDRRABSCHLUSS[1 + 1];
		 char    SKDABSCHLUSSEIL[1 + 1];
		 char    SKDTRENNALPHATEXT[1 + 1];
		 char    SKDRR0800[1 + 1];
		 char    SKDTRENNALPHAURR[1 + 1];
		 char    SKDORIGINALMELD[1 + 1];
		 char    SKDMIDAS[1 + 1];
       };

 struct O_KUNDESCHALTER {
		 char    IDFNR[11];
		 char    SKDWERBEFACHBELEGT[1];
		 char    SKDKDFACHAKTIV[1];
		 char    SKDNATRARESTAKZEPT[1];
		 char    SKDNETTOAKTION[1];
		 char    SKDETIKETTSERVICE[1];
		 char    SKDDEFEKTLIEFERN[1];
		 char    SKDDEFEKTABSAGEN[1];
		 char    SKDSAMMLDAFUE[1];
		 char    SKDAPOEKSTATISITIK[1];
		 char    SKDAUTOERHOEHGNNNR[1];
		 char    SKDDEFEKTMELDGAUSW[1];
		 char    SKDKONTRKOBELEGE[1];
		 char    SKDAUFTRAGZUSAMMEN[1];
		 char    SKDMWSTHALB[1];
		 char    SKDSTADTKUNDE[1];
		 char    SKDVALUTASPERRE[1];
		 char    SKDSCHWERPUNKT1[1];
		 char    SKDSCHWERPUNKT2[1];
		 char    SKDSCHWERPUNKT3[1];
		 char    SKDSCHWERPUNKT4[1];
		 char    SKDSCHWERPUNKT5[1];
		 char    SKDVERBUNDGANZ[1];
		 char    SKDABSCHLAGRECHN[1];
		 char    SKDKDKRITISCH[1];
		 char    SKDEILSPERRE[1];
		 char    SKDABSAGEN[1];
		 char    SKDVIPKUNDE[1];
		 char    SKDAUFTRAGSPLIT[1];
		 char    SKDMUSSKOPF[1];
		 char    SKDSEPAUFT[1];
		 char    SKDAUFTRAGZURUECK[1];
		 char    SKDBESTZEIT[1];
		 char    SKDWIRDBEARB[1];
		 char    KZUPD[1];
		 char    SKDREIMPORT[1];
		 char    SKDWARENACHLIEFERN[1];
		 char    SKDPINKUNDE[1];
		 char    SKDADGKUNDE[1];
		 char    SKDDRUCKBETAPHARM[1];
		 char    SKDFAX400[1];
		 char    SKDKUNDEAEGESPERRT[1];
		 char    SKDDRUCKETIKETT[1];
		 char    SKDDRUCKTIERARZNEI[1];
		 char    SKDDRUCKKAUFSTRUKT[1];
		 char    SKDKAUFSTRUKTART[1];
		 char    SKDMONATSRABATT[1];
		 char    SKDDRUCKUMSATZ[1];
		 char    VERTRIEBSZENTRUMNR[7];
		 char    KUNDENNR[11];
		 char    TM_DATE[11];
		 char    TM_TIME[11];
		 char    LOGINID[11];
		 char    CHANGEID[1];
		 char    SKDBLICKPUNKTABO[1];
		 char    SKDBUECHER[1];
		 char    SKDVERTRIEBBINDUNG[1];
		 char    SKDPOOL[1];
		 char    SKDBOUHON[1];
		 char    SKDROCHE[1];
		 char    SKDVICHY[1];
		 char    SKDVBFILIALEMELD[1];
		 char    SKDRRABSCHLUSS[1];
		 char    SKDABSCHLUSSEIL[1];
		 char    SKDTRENNALPHATEXT[1];
		 char    SKDRR0800[1];
		 char    SKDTRENNALPHAURR[1];
		 char    SKDORIGINALMELD[1];
		 char    SKDMIDAS[1];
       };

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif


#if defined (BUF_DESC)
 static struct buf_desc KUNDESCHALTER_BES [] =
 {
	 { TYP_L ,   11 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_S ,    6 ,   0 },
	 { TYP_L ,   11 ,   0 },
	 { TYP_L ,   11 ,   0 },
	 { TYP_L ,   11 ,   0 },
	 { TYP_L ,   11 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
	 { TYP_C ,    1 ,   0 },
 };
#elif defined (C_BUF_DESC)
 static struct buf_desc KUNDESCHALTER_BES [] =
 {
	 { TYP_L,   11 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_S,    5 ,   0 },
	 { TYP_L,   11 ,   0 },
	 { TYP_L,   11 ,   0 },
	 { TYP_L,   11 ,   0 },
	 { TYP_L,   11 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
	 { TYP_F,    1 ,   0 },
 };
#endif

#ifdef TRANSCLASS

 class CKUNDESCHALTER
 {
  public:

  KUNDESCHALTER s;
  char error_msg[81];
  int rc;

  void buf_default()
  {
   ::buf_default((void *) &s, KUNDESCHALTER_BES, KUNDESCHALTER_ANZ);
  }
  void Server(int fkt_nr, int pos=0)
  {
#ifdef WIN32
   rc=::ServerNr(pos,fkt_nr,(void *)&s,KUNDESCHALTER_BES, KUNDESCHALTER_ANZ, error_msg);
   #else
   rc=::Server(fkt_nr,(void *)&s,KUNDESCHALTER_BES, KUNDESCHALTER_ANZ, error_msg);
#endif
   if (rc<0) FehlerBehandlung( rc, error_msg );
  }
  CKUNDESCHALTER()
  {
   ::buf_default((void *)&s, KUNDESCHALTER_BES, KUNDESCHALTER_ANZ);
  }
 };
#endif

#define KUNDESCHALTER_CREATE(xxx)  EXEC SQL CREATE TABLE xxx (\
		 IDFNR              INTEGER         default 0 NOT NULL,\
		 SKDWERBEFACHBELEGT CHAR(1)         default " " NOT NULL,\
		 SKDKDFACHAKTIV     CHAR(1)         default " " NOT NULL,\
		 SKDNATRARESTAKZEPT CHAR(1)         default " " NOT NULL,\
		 SKDNETTOAKTION     CHAR(1)         default " " NOT NULL,\
		 SKDETIKETTSERVICE  CHAR(1)         default " " NOT NULL,\
		 SKDDEFEKTLIEFERN   CHAR(1)         default " " NOT NULL,\
		 SKDDEFEKTABSAGEN   CHAR(1)         default " " NOT NULL,\
		 SKDSAMMLDAFUE      CHAR(1)         default " " NOT NULL,\
		 SKDAPOEKSTATISITIK CHAR(1)         default " " NOT NULL,\
		 SKDAUTOERHOEHGNNNR CHAR(1)         default " " NOT NULL,\
		 SKDDEFEKTMELDGAUSW CHAR(1)         default " " NOT NULL,\
		 SKDKONTRKOBELEGE   CHAR(1)         default " " NOT NULL,\
		 SKDAUFTRAGZUSAMMEN CHAR(1)         default " " NOT NULL,\
		 SKDMWSTHALB        CHAR(1)         default " " NOT NULL,\
		 SKDSTADTKUNDE      CHAR(1)         default " " NOT NULL,\
		 SKDVALUTASPERRE    CHAR(1)         default " " NOT NULL,\
		 SKDSCHWERPUNKT1    CHAR(1)         default " " NOT NULL,\
		 SKDSCHWERPUNKT2    CHAR(1)         default " " NOT NULL,\
		 SKDSCHWERPUNKT3    CHAR(1)         default " " NOT NULL,\
		 SKDSCHWERPUNKT4    CHAR(1)         default " " NOT NULL,\
		 SKDSCHWERPUNKT5    CHAR(1)         default " " NOT NULL,\
		 SKDVERBUNDGANZ     CHAR(1)         default " " NOT NULL,\
		 SKDABSCHLAGRECHN   CHAR(1)         default " " NOT NULL,\
		 SKDKDKRITISCH      CHAR(1)         default " " NOT NULL,\
		 SKDEILSPERRE       CHAR(1)         default " " NOT NULL,\
		 SKDABSAGEN         CHAR(1)         default " " NOT NULL,\
		 SKDVIPKUNDE        CHAR(1)         default " " NOT NULL,\
		 SKDAUFTRAGSPLIT    CHAR(1)         default " " NOT NULL,\
		 SKDMUSSKOPF        CHAR(1)         default " " NOT NULL,\
		 SKDSEPAUFT         CHAR(1)         default " " NOT NULL,\
		 SKDAUFTRAGZURUECK  CHAR(1)         default " " NOT NULL,\
		 SKDBESTZEIT        CHAR(1)         default " " NOT NULL,\
		 SKDWIRDBEARB       CHAR(1)         default " " NOT NULL,\
		 KZUPD              CHAR(1)         default " " NOT NULL,\
		 SKDREIMPORT        CHAR(1)         default " " NOT NULL,\
		 SKDWARENACHLIEFERN CHAR(1)         default " " NOT NULL,\
		 SKDPINKUNDE        CHAR(1)         default " " NOT NULL,\
		 SKDADGKUNDE        CHAR(1)         default " " NOT NULL,\
		 SKDDRUCKBETAPHARM  CHAR(1)         default " " NOT NULL,\
		 SKDFAX400          CHAR(1)         default " " NOT NULL,\
		 SKDKUNDEAEGESPERRT CHAR(1)         default " " NOT NULL,\
		 SKDDRUCKETIKETT    CHAR(1)         default " " NOT NULL,\
		 SKDDRUCKTIERARZNEI CHAR(1)         default " " NOT NULL,\
		 SKDDRUCKKAUFSTRUKT CHAR(1)         default " " NOT NULL,\
		 SKDKAUFSTRUKTART   CHAR(1)         default " " NOT NULL,\
		 SKDMONATSRABATT    CHAR(1)         default " " NOT NULL,\
		 SKDDRUCKUMSATZ     CHAR(1)         default " " NOT NULL,\
		 VERTRIEBSZENTRUMNR SMALLINT        default 0 NOT NULL,\
		 KUNDENNR           INTEGER         default 0 NOT NULL,\
		 TM_DATE            INTEGER         default 0 NOT NULL,\
		 TM_TIME            INTEGER         default 0 NOT NULL,\
		 LOGINID            INTEGER         default 0 NOT NULL,\
		 CHANGEID           CHAR(1)         default " " NOT NULL,\
		 SKDBLICKPUNKTABO   CHAR(1)         default " " NOT NULL,\
		 SKDBUECHER         CHAR(1)         default " " NOT NULL,\
		 SKDVERTRIEBBINDUNG CHAR(1)         default " " NOT NULL,\
		 SKDPOOL            CHAR(1)         default " " NOT NULL,\
		 SKDBOUHON          CHAR(1)         default " " NOT NULL,\
		 SKDROCHE           CHAR(1)         default " " NOT NULL,\
		 SKDVICHY           CHAR(1)         default " " NOT NULL,\
		 SKDVBFILIALEMELD   CHAR(1)         default " " NOT NULL,\
		 SKDRRABSCHLUSS     CHAR(1)         default " " NOT NULL,\
		 SKDABSCHLUSSEIL    CHAR(1)         default " " NOT NULL,\
		 SKDTRENNALPHATEXT  CHAR(1)         default " " NOT NULL,\
		 SKDRR0800			CHAR(1)         default " " NOT NULL,\
		 SKDTRENNALPHAURR	CHAR(1)         default " " NOT NULL,\
		 SKDORIGINALMELD	CHAR(1)         default " " NOT NULL,\
		 SKDMIDAS			CHAR(1)         default " " NOT NULL  ) EXTENT SIZE 9 LOCK MODE ROW;

#define KUNDESCHALTER_CREATE_INDEX(yyy,xxx) \

#define KUNDESCHALTER_DELETE_INDEX(xxx) \

