#ifndef G_LIARTIK_INCLUDED
#define G_LIARTIK_INCLUDED

long GenLiArtNeu( char *db, char *ili_direc, char *errmld );

long tages_datum;

int  Fd_Clioart;
int  Fd_Cliart;
int  Fd_Clicompany;
int  Fd_Cliohsatz;
int  Fd_Clihsatz;
int  Fd_Cassortmentcode;
int	 Fd_Catccode;
int  Fd_Cliproduct;
int  Fd_Cliproductgrp;

#define MSGTYPE_ART					"010"
#define MSGTYPE_ARTCOMP				"011"
#define MSGTYPE_ARTBAR				"012"
#define MSGTYPE_ARTCH				"013"
#define MSGTYPE_ARTPRI				"014"
#define MSGTYPE_ARTMIG				"015" 
#define MSGTYPE_ARTDAN				"016"
#define MSGTYPE_ARTLIM				"017"
#define MSGTYPE_ARTINS				"018"
#define MSGTYPE_SDS					"019"
#define MSGTYPE_PRD					"040"
#define MSGTYPE_PRD_CPT				"041"
#define MSGTYPE_COMPANY				"090"
#define MSGTYPE_CODE				"160"
#define MSGTYPE_ARTPRI_NEW			"180"
#define MSGTYPE_ARTSL				"922"
#define MSGTYPE_ARTADR				"920"
#define MSGTYPE_REGULATIONS			"923"

#define NO_FIELDS_ART			62
#define NO_FIELDS_ARTCOMP		7
#define NO_FIELDS_ARTBAR		7
#define NO_FIELDS_ARTCH			7
#define NO_FIELDS_ARTPRI		5
#define NO_FIELDS_ARTMIG		8
#define NO_FIELDS_ARTDAN		5
#define NO_FIELDS_ARTLIM		3
#define NO_FIELDS_ARTINS		7
#define NO_FIELDS_PRD			76
#define NO_FIELDS_COMPANY		18
#define NO_FIELDS_CODES			11
#define NO_FIELDS_SDS			6
#define NO_FIELDS_ARTSL			10
#define NO_FIELDS_ARTADR		9
#define NO_FIELDS_REGULATIONS   4  // +1 wegen Zählerwert

typedef enum EMsgType
{
	UNKNOWN				= 0,
	ARTICLE_ART			= 10,
	ARTICLE_ARTCOMP		= 11,
	ARTICLE_ARTBAR		= 12,
	ARTICLE_ARTCH		= 13,
	ARTICLE_ARTPRI		= 14,
	ARTICLE_ARTMIG		= 15,
	ARTICLE_ARTDAN		= 16,
	ARTICLE_ARTLIM		= 17,
	ARTICLE_ARTINS		= 18,
	ARTICLE_SDS			= 19,
	PRODUCT_PRD			= 40,	
	PRODUCT_PRD_CPT		= 41,	
	COMPANY				= 90,
	CODE				= 160,
	ARTICLE_ARTPRI_NEW	= 180,
	ARTICLE_ARTSL		= 922,
	ARTICLE_ARTADR		= 920,
	ARTICLE_REGULATIONS	= 923,
} EMsgType;

typedef enum EArticleArtRecordField
{
	ART_MSGTYPE = 0,
	ART_PHAR,
	ART_PHARMACODE,
	ART_GTIN,
	ART_GRPCD,
	ART_CDSO1,
	ART_CDSO2,
	ART_PRDNO,
	ART_SMCAT,
	ART_SMNO,
	ART_HOSPCD,
	ART_CLINCD,
	ART_ARTTYP,
	ART_VAT,
	ART_SALECD,
	ART_GRDFR,
	ART_COOL,
	ART_TEMP,
	ART_CDBG,
	ART_BG,
	ART_EXP,
	ART_QTY,
	ART_DSCRD,
	ART_DSCRF,
	ART_DSCRLONGD,
	ART_DSCRLONGF,
	ART_SORTD,
	ART_SORTF,
	ART_QTYUD,
	ART_QTYUF,
	ART_IMG2,
	ART_DSCRPACKD,
	ART_DSCRPACKF,
	ART_PCKTYPCD,
	ART_PCKTYPD,
	ART_PCKTYPF,
	ART_MULT,
	ART_SYN1D,
	ART_SYN1F,
	ART_NOPCS,
	ART_HSCD,
	ART_MINI,
	ART_DEPCD,
	ART_DEPOT,
	ART_LOACD,
	ART_OUTSAL,
	ART_STTOX,
	ART_NOTI,
	ART_GGL,
	ART_CE,
	ART_SMDAT,
	ART_SMCDAT,
	ART_SIST,
	ART_ESIST,
	ART_BIOCID,
	ART_BAGNO,
	ART_LIGHT,
	ART_TRADEABLE,
	ART_WEIGHT,
	ART_COLDCHAIN,
	ART_FOODINFO,
	ART_DEL
} EArticleArtRecordField;

enum EArticleCompanyField
{
	ARTCOMP_MSGTYPE = 0,
	ARTCOMP_PARENTKEY,
	ARTCOMP_COMPNO,
	ARTCOMP_ROLE,
	ARTCOMP_ARTNO1,
	ARTCOMP_ARTNO2,
	ARTCOMP_ARTNO3
} ;

enum EArticleBarcodeField
{
	ARTBAR_MSGTYPE = 0,
	ARTBAR_PARENTKEY,
	ARTBAR_CDTYP,
	ARTBAR_BC,
	ARTBAR_BCSTAT,
	ARTBAR_PHAR2,
	ARTBAR_PHARMACODE2
};

enum EArticleChainingField
{
	ARTCH_MSGTYPE = 0,
	ARTCH_PARENTKEY,
	ARTCH_PHAR2,
	ARTCH_PHARMACODE2,
	ARTCH_CHTYPE,
	ARTCH_LINENO,
	ARTCH_NOUNITS
};

enum EArticlePriceInformationField
{
	ARTPRI_MSGTYPE = 0,
	ARTPRI_PARENTKEY,
	ARTPRI_VDAT,
	ARTPRI_PTYP,
	ARTPRI_PRICE
};

enum EArticleMiGelField
{
	ARTMIG_MSGTYPE = 0,
	ARTMIG_PARENTKEY,
	ARTMIG_VDAT,
	ARTMIG_MIGCD,
	ARTMIG_LINENO,
	ARTMIG_PTYP,
	ARTMIG_MIGPRI,
	ARTMIG_VDATPRI
};

enum EArticleInsuranceCodeField
{
	ARTINS_MSGTYPE = 0,
	ARTINS_PARENTKEY,
	ARTINS_VDAT,
	ARTINS_INCD,
	ARTINS_NINCD
};

enum EArticleDangerCodeField
{
	ARTDAN_MSGTYPE = 0,
	ARTDAN_PARENTKEY,
	ARTDAN_CDTYP,
	ARTDAN_LINENO,
	ARTDAN_CDVAL
};

enum EArticleSdsField
{
	SDS_MSGTYPE = 0,
	SDS_PARENTKEY,
	SDS_DE,
	SDS_FR,
	SDS_IT,
	SDS_EN
};

enum EProductGrpEntryField
{
	PRDGRP_MSGTYPE = 0,
	PRDGRP_PRDNO,
	PRDGRP_CPTLNO,
	PRDGRP_CNAMED, 
	PRDGRP_CNAMEF,
	PRDGRP_IDXIND,
	PRDGRP_DDDD,
	PRDGRP_DDDU,
	PRDGRP_DDDA,
	PRDGRP_IDXIA,
	PRDGRP_IXREL,
	PRDGRP_GALF,
	PRDGRP_DRGGRPCD,
	PRDGRP_PRDGRPCD,
	PRDGRP_PRBSUIT,
	PRDGRP_CSOLV,
	PRDGRP_SOLVQ,
	PRDGRP_SOLVQU,
	PRDGRP_PHVAL,
	PRDGRP_LSPNSOL,
	PRDGRP_APDURSOL,
	PRDGRP_EXCIP,
	PRDGRP_EXCIPQ,
	PRDGRP_EXCIPCD,
	PRDGRP_EXCIPCF,
	PRDGRP_PQTY,
	PRDGRP_PQTYU,
	PRDGRP_STDPRESCU,
	PRDGRP_SIZEMM,
	PRDGRP_WEIGHT,
	PRDGRP_LOOKD,
	PRDGRP_LOOKF,
	PRDGRP_IMG2
};

enum EProductEntryField
{
	PRD_MSGTYPE = 0,
	PRD_PRDNO,
	PRD_DSCRD,
	PRD_DSCRF,
	PRD_DSCRLONGD,
	PRD_DSCRLONGF,
	PRD_BNAMD,
	PRD_BNAMF,
	PRD_BNAMLONGD,
	PRD_BNAMLONGF,
	PRD_ADNAMD,
	PRD_ADNAMF,
	PRD_ADNAMLONGD,
	PRD_ADNAMLONGF,
	PRD_SIZE,
	PRD_ADINFD,
	PRD_ADINFF,
	PRD_ADINFLONGD,
	PRD_ADINFLONGF,
	PRD_DSCRSWISSMEDICD,
	PRD_DSCRSWISSMEDICF,
	PRD_GENCD,
	PRD_GENGRP,
	PRD_ATC,
	PRD_IT,
	PRD_ITBAG,
	PRD_KONO,
	PRD_TRADE,
	PRD_CDBRAND,
	PRD_CDBRANDSUB,
	PRD_PRTNO,
	PRD_PRTNO2,
	PRD_MONO,
	PRD_CDGALD,
	PRD_CDGALF,
	PRD_FORMD,
	PRD_FORMF,
	PRD_DOSE,
	PRD_DOSEU,
	PRD_DRGFD,
	PRD_DRGFF,
	PRD_ORPH,
	PRD_BIOPHA,
	PRD_BIOSIM,
	PRD_BFS,
	PRD_BLOOD,
	PRD_MSCD,
	PRD_PRDIXREL,
	PRD_CDS,
	PRD_SYND,
	PRD_SYNF,
	PRD_KP,
	PRD_BFSDATA,
	PRD_DRGPRICEY,
	PRD_QAP,
	PRD_BFSDAT, 
	PRD_BFSCDAT, 
	PRD_DRGPRICEYDAT, 
	PRD_DRGPRICEYCDAT, 
	PRD_MDCLASS, 
	PRD_MDNB, 
	PRD_CDSMODULES, 
	PRD_SMNR, 
	PRD_SMCAT, 
	PRD_STREHA, 
	PRD_STREHADAT, 
	PRD_STREHACDAT, 
	PRD_STREHAPRICEY, 
	PRD_STREHAPRICEYDAT, 
	PRD_STRREHAPRICEYCDAT, 
	PRD_EXPORTONLY, 
	PRD_LTC_ASC, 
	PRD_TR,
	PRD_SMNAS, 
	PRD_KIDO, 
	PRD_AAP,
	PRD_GMN,
	PRD_MDATTR,
	PRD_PPLUS,
	PRD_UFI,
	PRD_DEL
};

enum ECompanyField
{
	CP_MSGTYPE = 0,
	CP_PRTNO,
	CP_NAMS,
	CP_NAML,
	CP_ADNAM,
	CP_STRT,
	CP_ZIP,
	CP_CITY,
	CP_CNTRY,
	CP_PBOX,
	CP_TEL,
	CP_FAX,
	CP_CNTCT,
	CP_EMAIL,
	CP_WWW,
	CP_GLN,
	CP_APPENDIX,
	CP_DEL
};

enum ECodeField
{
	CD_MSGTYPE = 0,
	CD_TYP,
	CD_VAL,
	CD_DSCRSD,
	CD_DSCRSF,
	CD_DSCRMD,
	CD_DSCRMF,
	CD_DSCRD,
	CD_DSCRF,
	CD_PV,
	CD_DEL
};
 
typedef enum EArtAdrField
{
	ARTADR_MSGTYPE = 0,
	ARTADR_PARENTKEY,
	ARTADR_ADRVAL,
	ARTADR_ENVHAZARD,
	ARTADR_NETQTY,
	ARTADR_NETQTYU,
	ARTADR_UNREC,
	ARTADR_HAZARDINDUCERD,
	ARTADR_ADRPACKAGE
} EArtAdrField;

typedef enum ERegulationsField
{
	REGU_MSGTYPE = 0,
	REGU_PARENTKEY,
	PINT_COUNTER,
	REGU_REGULATION
} ERegulationsField;

typedef enum EArtSlField
{
	ARTSL_MSGTYPE = 0,
	ARTSL_PARENTKEY,
	ARTSL_BAGDOSSIER,
	ARTSL_BAGSL,
	ARTSL_BAGSLC,
	ARTSL_INSLIM,
	ARTSL_LIMPTS,
	ARTSL_SLOPLUS,
	ARTSL_LIM_VDAT,
	ARTSL_SLOPLUS_VDAT
} EArtSlField;

typedef enum EArticlePrice
{
	ARTPRICE_MSGTYPE = 0,
	ARTPRICE_PHARMACODE,
	ARTPRICE_PRTNO,
	ARTPRICE_PTYP,
	ARTPRICE_VDAT,
	ARTPRICE_PRICE,
	ARTPRICE_MIGCD
} EArticlePrice;

int  m_eFileArt;
char m_szEUHazard[51];

int  line_pos;
int  update_cliart;
int  pricetype_exf;
int  bctype_ean;
int  pzn_current;
short  clio_exists;

int Trim (char *s);
int TestEanNr( char *ean );

long lidatumnr;

#endif
