//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZdpDruck.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ZDPDRUCKTYPE                129
#define IDB_BM_KNOEDEL                  130
#define IDD_SERVER                      131
#define IDD_USER                        132
#define IDB_BM_VOGESE                   149
#define IDD_RECHTE                      150
#define IDB_BM_RIGHTS                   151
#define IDB_BM_PASSWD                   153
#define IDD_ARTBLIE                     154
#define IDD_ARTHERS                     155
#define IDD_SELECTDLG1                  158
#define IDB_BM_SUCHE                    159
#define IDB_BM_RUEBL                    160
#define IDB_BM_VORBL                    161
#define IDB_BM_RUEBL1                   162
#define IDB_BM_VORBL1                   163
#define IDB_BM_SUCHE1                   164
#define IDD_DRUCK                       165
#define IDD_NEMWART                     166
#define IDD_NEMWLIEF                    167
#define IDD_LINEPROT                    168
#define IDD_ART7PROZ                    169
#define IDD_ARTSPERR                    170
#define IDD_NONEMLIE                    171
#define IDD_INKONS                      172
#define IDD_PERHOEH                     173
#define IDD_PERHABVK                    174
#define IDD_GHAEN                       176
#define IDD_AMBLIEF                     177
#define IDD_DC_PREISAEND                178
#define IDD_DIALOG1                     179
#define IDD_GALDAT_NEU                  179
#define IDD_GALDAT_AH                   180
#define IDD_ELEKTRO_AEND                181
#define IDD_ELEKTRONEU                  182
#define IDD_HERSTELLERCODE              183
#define IDC_USER_NAME                   1001
#define IDC_USER_PASSWD                 1002
#define IDC_ABOUT_VERSION               1066
#define IDC_ABOUT_DATE                  1067
#define IDC_ABOUT_KNOEDEL               1068
#define IDC_ABOUT_PB                    1069
#define IDC_RECHTE_CB_USERNAME          1070
#define IDC_RECHTE_RB_NONE              1071
#define IDC_RECHTE_RB_READ              1072
#define IDC_RECHTE_RB_WRITE             1073
#define IDC_RECHTE_ST_MEN_MUSTER        1074
#define IDC_RECHTE_ST_REG_MUSTER        1075
#define IDC_RECHTE_BP_SPEICHERN         1076
#define IDC_RECHTE_BP_COPY              1077
#define IDC_RECHTE_BP_PASTE             1078
#define IDC_RECHTE_CK_SUBSUPER          1079
#define IDC_RECHTE_BP_SUPER             1080
#define IDC_ARTBLIE_SUCHB               1090
#define IDC_ARTBLIE_GRID                1091
#define IDC_ARTHERS_SUCHB               1092
#define IDC_ARTHERS_GRID                1093
#define IDC_ST_SELECTDIALOG_AUSWAHL     1094
#define IDC_CB_SELECTDIALOG_AUSWAHL     1095
#define IDC_EDIT_SUCHB1_1               1096
#define IDC_EDIT_SUCHB1_2               1097
#define IDC_STATIC_SUCHB1_1             1098
#define IDC_STATIC_SUCHB1_2             1099
#define IDC_STATIC_FRAGE1_1             1100
#define IDC_STATIC_FRAGE1_2             1101
#define IDC_SUCHE                       1102
#define IDC_VORBL                       1103
#define IDC_RUEBL                       1104
#define IDC_LISTCTRL_BOX                1105
#define IDC_ARTHERS_SHOW                1106
#define IDC_ARTBLIE_SHOW                1107
#define IDC_ARTBLIE_RD_NR               1108
#define IDC_ARTBLIE_RD_NAME             1109
#define IDC_ARTHERS_RD_NR               1110
#define IDC_ARTHERS_RD_NAME             1111
#define IDC_NEMWART_DATBIS              1112
#define IDC_NEMWART_GRID                1113
#define IDC_NEMWART_DATVON              1114
#define IDC_NEMWLIEF_GRID               1115
#define IDC_NEMWLIEF_DATVON             1116
#define IDC_NEMWLIEF_DATBIS             1117
#define IDC_ART7PROZ_GRID               1118
#define IDC_ART7PROZ_DATVON             1119
#define IDC_ART7PROZ_DATBIS             1120
#define IDC_ARTSPERR_DATVON             1121
#define IDC_ARTSPERR_DATBIS             1122
#define IDC_ARTSPERR_GRID               1123
#define IDC_NONEMLIE_DATVON             1124
#define IDC_NONEMLIE_DATBIS             1125
#define IDC_NONEMLIE_GRID               1126
#define IDC_INKONS_GRID                 1127
#define IDC_INKONS_DATVON               1128
#define IDC_INKONS_DATBIS               1129
#define IDC_PERHOEH_DATVON              1130
#define IDC_PERHOEH_DATBIS              1131
#define IDC_PERHOEH_GRID                1132
#define IDC_PERHABVK_GRID               1133
#define IDC_PERHABVK_DATBIS             1134
#define IDC_PERHABVK_DATVON             1135
#define IDC_PERHABVK_REGION             1136
#define IDC_PERHABVK_BRANCH             1137
#define IDC_PERHABVK_FILZU              1139
#define IDC_GHAEN_GRID                  1143
#define IDC_GHAEN_DATVON                1144
#define IDC_GHAEN_DATBIS                1145
#define IDC_AMBLIEF_GRID                1146
#define IDC_DC_GRID                     1147
#define IDC_VZ                          1148
#define IDC_GALDAT_GRID                 1149
#define IDC_DATVON                      1150
#define IDC_DATBIS                      1151
#define IDC_ELEKTRO_GRID                1152
#define IDC_HERSTELLER_GRID             1153
#define IDC_CODE                        1154
#define IDC_HERSTELLERCODE              1154
#define IDC_SCROLLBAR1                  1155
#define IDC_SERVER_SERVER               1273
#define IDC_SERVER_DBASE                1274
#define IDC_PROT_MODE1                  1366
#define IDC_PROT_MODE2                  1367
#define IDC_PROT_MODE3                  1368
#define IDC_PROT_FILE                   1369
#define ID_TASCHENRECHNER               32771
#define ID_SERVER                       32772
#define ID_VIEW_MS_STANDARD             32773
#define ID_VIEW_AUTO_FRAGE              32774
#define ID_VIEW_CUSTTOOLBAR             32775
#define ID_RECORD_UNDO                  32781
#define ID_RECORD_CUT                   32782
#define ID_RECORD_COPY                  32783
#define ID_RECORD_PASTE                 32784
#define ID_RECORD_SEARCH                32785
#define ID_RECORD_SAVE                  32786
#define ID_RECORD_DELETE                32787
#define ID_RECORD_NEW                   32788
#define ID_VIEW_RECHTE                  32797
#define ID_ARTBLIE                      32799
#define ID_HERST                        32800
#define ID_ARTHERS                      32801
#define ID_NEMWART                      32806
#define ID_NEMWLIE                      32807
#define ID_FILE_SPEICHERN               32808
#define ID_CLIENT_PROTO                 32809
#define ID_BUFFERED_OFF                 32810
#define ID_BUFFERED_ON                  32811
#define ID_COMPRESS_OFF                 32812
#define ID_COMPRESS_ON1                 32813
#define ID_COMPRESS_ON2                 32814
#define ID_ART7PROZ                     32815
#define ID_ARTSPERR                     32817
#define ID_NONEMLIE                     32818
#define ID_INKONS                       32819
#define ID_PERHOEH                      32823
#define ID_PERHABVK                     32824
#define ID_PERHABVK_HS                  32825
#define ID_GHAEN_HS                     32826
#define ID_GHAEN                        32827
#define ID_AMBLIEF                      32828
#define ID_ARTIKELLISTEN_DATACARE       32830
#define ID_DC_PREISAEND                 32832
#define ID_ARTIKELLISTEN_GALDAT         32833
#define ID_GALDATNEU                    32835
#define ID_GALDATAH                     32837
#define ID_NEMLISTEN_                   32838
#define ID_ELEKTROWART                  32841
#define ID_ELEKTRO_NEUAUFN              32842
#define ID_HERSTELLERLISTEN_HERSTELLERCODE 32845
#define ID_PSENKABVK                    32847
#define IDS_TB_COMBO_0                  58000
#define IDS_TB_COMBO_1                  58001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
