#ifndef __PP_CSCORDERIBTPICKINGDATA_H_
#define __PP_CSCORDERIBTPICKINGDATA_H_


#define CSCORDERIBTPICKINGDATA_LISTE_390 \
        CSCORDERNO,\
        CSCORDERPOSNO,\
        DELIVERYPOSNO,\
        QUANTITY,\
        BATCH,\
        EXPIRYDATE

#define CSCORDERIBTPICKINGDATA_PLISTE \
        "CSCORDERIBTPICKINGDATA.CSCORDERNO,"\
        "CSCORDERIBTPICKINGDATA.CSCORDERPOSNO,"\
        "CSCORDERIBTPICKINGDATA.DELIVERYPOSNO,"\
        "CSCORDERIBTPICKINGDATA.QUANTITY,"\
        "CSCORDERIBTPICKINGDATA.BATCH,"\
        "CSCORDERIBTPICKINGDATA.EXPIRYDATE"

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

typedef struct N_CSCORDERIBTPICKINGDATA {
	long CSCORDERNO;
	long CSCORDERPOSNO;
	long DELIVERYPOSNO;
	long QUANTITY;
	char BATCH[26];
	long EXPIRYDATE;
} cscorderibtpickingdataS;

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif
#endif   // GUARD
