#ifndef __PP_CSCORDERPOSSPLITTINFO_H_
#define __PP_CSCORDERPOSSPLITTINFO_H_


#define CSCORDERPOSSPLITTINFO_LISTE_390 \
        CSCORDERNO,\
        CSCORDERPOSNO,\
        SPLITTTYPE,\
        ORIGINAL,\
        ORDERNO,\
        POSNO

#define CSCORDERPOSSPLITTINFO_PLISTE \
        "CSCORDERPOSSPLITTINFO.CSCORDERNO,"\
        "CSCORDERPOSSPLITTINFO.CSCORDERPOSNO,"\
        "CSCORDERPOSSPLITTINFO.SPLITTTYPE,"\
        "CSCORDERPOSSPLITTINFO.ORIGINAL,"\
        "CSCORDERPOSSPLITTINFO.ORDERNO,"\
        "CSCORDERPOSSPLITTINFO.POSNO"

#ifdef ESQL_C
EXEC SQL BEGIN DECLARE SECTION;
#endif

typedef struct N_CSCORDERPOSSPLITTINFO {
		long CSCORDERNO;
		long CSCORDERPOSNO;
		short SPLITTTYPE;
		short ORIGINAL;
		long ORDERNO;
		long POSNO;
} cscorderpossplittinfoS;

#ifdef ESQL_C
EXEC SQL END DECLARE SECTION;
#endif
#endif   // GUARD
