#! /usr/bin/ksh
set -x
cd $(dirname $0)/../bin

pwd

$(basename $0) $1 $2 $3
rc=$?
if [[ $rc -ne 0 ]]
then
   echo "$(basename $0) mit Fehler $rc abgebrochen"
   exit $rc
fi

mv $3/mwe.txt $3/archiv/mwe_${4}.txt
rc=$?

compress -f $3/archiv/mwe_${4}.txt

exit $rc
