#ifndef GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_INFRASTRUCTURE_SETUP_IMAINWAREHOUSEARTICLESRELEVANTCALCULATORLOGINGETTERCONSTPTR_H
#define GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_INFRASTRUCTURE_SETUP_IMAINWAREHOUSEARTICLESRELEVANTCALCULATORLOGINGETTERCONSTPTR_H

#include <boost/shared_ptr.hpp>

namespace mainwarehousearticlesrelevantcalculator
{
    namespace infrastructure
    {
        namespace setup
        {
            class IMAINWAREHOUSEARTICLESRELEVANTCALCULATORLoginGetter;
            typedef boost::shared_ptr< IMAINWAREHOUSEARTICLESRELEVANTCALCULATORLoginGetter const> IMAINWAREHOUSEARTICLESRELEVANTCALCULATORLoginGetterConstPtr;
        }
    }
}

#endif // GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_INFRASTRUCTURE_SETUP_IMAINWAREHOUSEARTICLESRELEVANTCALCULATORLOGINGETTERCONSTPTR_H
