#ifndef GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_COMPONENTMANAGER_MAINWAREHOUSEARTICLESRELEVANTCALCULATORAPPLCOMPMGRPTR_H
#define GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_COMPONENTMANAGER_MAINWAREHOUSEARTICLESRELEVANTCALCULATORAPPLCOMPMGRPTR_H

#include <boost/shared_ptr.hpp>

namespace mainwarehousearticlesrelevantcalculator
{
    namespace componentManager
    {
        class ApplCompMgr;
        typedef boost::shared_ptr< ApplCompMgr > ApplCompMgrPtr;
    }
}

#endif //GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_COMPONENTMANAGER_MAINWAREHOUSEARTICLESRELEVANTCALCULATORAPPLCOMPMGRPTR_H
