#ifndef GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_COMPONENTMANAGER_MAINWAREHOUSEARTICLESRELEVANTCALCULATORINFRASTRUCTURECOMPMGRPTR_H
#define GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_COMPONENTMANAGER_MAINWAREHOUSEARTICLESRELEVANTCALCULATORINFRASTRUCTURECOMPMGRPTR_H

#include <boost/shared_ptr.hpp>

namespace mainwarehousearticlesrelevantcalculator
{
    namespace componentManager
    {
        class InfrastructureCompMgr;
        typedef boost::shared_ptr< InfrastructureCompMgr > InfrastructureCompMgrPtr;
    }
}

#endif //GUARD_MAINWAREHOUSEARTICLESRELEVANTCALCULATOR_COMPONENTMANAGER_MAINWAREHOUSEARTICLESRELEVANTCALCULATORINFRASTRUCTURECOMPMGRPTR_H
